rule train_cl:
    params:
        bkg = '/eos/home-e/egovorko/kd_data/datasets_-1.npz',
        bkg_ids = '/eos/home-e/egovorko/kd_data/background_IDs_-1.npz',
        anomaly = '/eos/home-e/egovorko/kd_data/bsm_datasets_-1.npz',
        divisions = [0.30, 0.30, 0.20, 0.20]
    output:
        scaling = 'output/scaling.npz',
        dataset = 'output/embedding.npz',
        model = 'output/vae.pth'
    shell:
        'python cl/train.py {params.bkg} {params.bkg_ids} {params.anomaly} \
            --model-name {output.model} \
            --scaling-file {output.scaling} \
            --output-filename {output.dataset} '

rule train_nf:
    input:
    output:
    shell:
        'python nf/train.py'

rule plot:
    input:
    output:
